#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export GOPATH="$shome"

  cd "$shome"

  if [[ ! -d "$shome/src/github.com/gliderlabs/registrator" ]]; then
    git clone git@github.com:gliderlabs/registrator "$shome/src/github.com/gliderlabs/registrator"
  fi
  pushd "$shome/src/github.com/gliderlabs/registrator"
  git fetch
  git reset --hard "v${REGISTRATOR_VERSION}"
  popd

  if [[ ! -d "$shome/src/github.com/ugorji/go" ]]; then
    git clone git@github.com:ugorji/go "$shome/src/github.com/ugorji/go"
  fi

  pushd "$shome/src/github.com/ugorji/go"
  git fetch
  git reset --hard 8c0409f
  popd

  go get github.com/gliderlabs/registrator
}

main "$@"
