#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  export GOPATH="$shome"

  cd "$shome"

  if [[ ! -d "$shome/src/github.com/gliderlabs/registrator" ]]; then
    git clone -b "v${REGISTRATOR_VERSION}" git@github.com:gliderlabs/registrator "$shome/src/github.com/gliderlabs/registrator"
  fi

  if [[ ! -d "$shome/src/github.com/ugorji/go" ]]; then
    git clone -b 8c0409f git@github.com:ugorji/go "$shome/src/github.com/ugorji/go"
  fi

  go get github.com/gliderlabs/registrator
}

main "$@"
