#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if ! type -P registrator >/dev/null; then
    return 1
  fi

  return 0
}

main "$@"
