#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_registrator="0.0.1"
  jq -n --arg registrator "$ver_registrator" '{registrator: $registrator}'
}

version "$@"
